version: 1.0.{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
only_commits:
  files:
    - cli.appveyor.yml
    - src/CLI/
    - src/Shared/Polyrific.Catapult.Shared.ApiClient/
    - src/Shared/Polyrific.Catapult.Shared.Dto/
    - src/Shared/Polyrific.Catapult.Shared.Service/
    - tests/Polyrific.Catapult.Cli.UnitTests/
configuration: Release
dotnet_csproj:
  patch: true
  file: '**/Polyrific.Catapult.Cli.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/CLI/Polyrific.Catapult.Cli/Polyrific.Catapult.Cli.csproj
build_script:
  - cmd: dotnet publish ./src/CLI/Polyrific.Catapult.Cli/Polyrific.Catapult.Cli.csproj
test_script:
  - cmd: dotnet test ./tests/Polyrific.Catapult.Cli.UnitTests/Polyrific.Catapult.Cli.UnitTests.csproj
artifacts:
  - path: 'src/CLI/Polyrific.Catapult.Cli/bin/$(configuration)/publish/'
    name: CLI
    type: zip
deploy: off