site_name: OpenCatapult Docs
site_description: Documentation of open source Catapult project
copyright: Copyright (c) Polyrific, Inc 2018. All rights reserved.
repo_url: https://github.com/Polyrific-Inc/OpenCatapult
nav:
  - Home: 'index.md'
  - Command Line Interface:
    - Overview: 'cli/cli.md'
    - Account: 'cli/account.md'
    - Engine: 'cli/engine.md'
    - Job: 'cli/job.md'
    - Member: 'cli/member.md'
    - Model: 'cli/model.md'
    - Project: 'cli/project.md'
    - Property: 'cli/property.md'
    - Queue: 'cli/queue.md'
    - Task: 'cli/task.md'
  - Web UI: 
    - Overview: 'webui/webui.md'
  - Mobile: 
    - Overview: 'mobile/mobile.md'
  - API: 
    - Overview: 'api/api.md'
  - Engine: 
    - Overview: 'engine/engine.md'
  - Plugins: 
    - Overview: 'plugins/plugins.md'
  - About: 'about.md'
theme: 
  name: readthedocs
  custom_dir: docs/custom/