version: 1.0.0-alpha-{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
only_commits:
  files:
    - appveyor/engine.appveyor.yml
    - src/Engine/
    - src/Shared/Polyrific.Catapult.Shared.ApiClient/
    - src/Shared/Polyrific.Catapult.Shared.Common/
    - src/Shared/Polyrific.Catapult.Shared.Dto/
    - src/Shared/Polyrific.Catapult.Shared.Service/
    - tests/Polyrific.Catapult.Engine.UnitTests/
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\Polyrific.Catapult.Engine.csproj'
  version: '{version}'
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/Engine/Polyrific.Catapult.Engine/Polyrific.Catapult.Engine.csproj
build_script:
  - cmd: dotnet publish ./src/Engine/Polyrific.Catapult.Engine/Polyrific.Catapult.Engine.csproj
test_script:
  - cmd: dotnet test ./tests/Polyrific.Catapult.Engine.UnitTests/Polyrific.Catapult.Engine.UnitTests.csproj
artifacts:
  - path: 'src/Engine/Polyrific.Catapult.Engine/bin/$(configuration)/publish/'
    name: Engine
    type: zip
deploy: off