version: 1.0.0.{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
only_commits:
  files:
    - appveyor/plugin-dotnetcoretest.appveyor.yml
    - src/Plugins/TestProvider/DotNetCoreTest/
    - src/Plugins/Polyrific.Catapult.Plugins.Abstraction/
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\DotNetCoreTest.csproj'
  version: '{version}'
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/Plugins/TestProvider/DotNetCoreTest/src/DotNetCoreTest.csproj
build_script:
  - cmd: dotnet publish ./src/Plugins/TestProvider/DotNetCoreTest/src/DotNetCoreTest.csproj -o ../publish
test_script:
  - cmd: dotnet test ./src/Plugins/TestProvider/DotNetCoreTest/tests/DotNetCoreTest.Tests.csproj
artifacts:
  - path: 'src/Plugins/TestProvider/DotNetCoreTest/publish/'
    name: TestProvider-DotNetCoreTest
    type: zip
deploy: off