version: 1.0.{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
only_commits:
  files:
    - appveyor/plugin-dotnetcore.appveyor.yml
    - src/Plugins/BuildProvider/DotNetCore/
    - src/Plugins/Polyrific.Catapult.Plugins.Abstraction/
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\DotNetCore.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/Plugins/BuildProvider/DotNetCore/src/DotNetCore.csproj
build_script:
  - cmd: dotnet publish ./src/Plugins/BuildProvider/DotNetCore/src/DotNetCore.csproj -o ../publish
test_script:
  - cmd: dotnet test ./src/Plugins/BuildProvider/DotNetCore/tests/DotNetCore.Tests.csproj
artifacts:
  - path: 'src/Plugins/BuildProvider/DotNetCore/publish/'
    name: BuildProvider-DotNetCore
    type: zip
deploy: off